/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiSettings: typeof import('./src/components/ai/AiSettings.vue')['default']
    AppLogo: typeof import('./src/components/common/AppLogo.vue')['default']
    CommandPalette: typeof import('./src/components/terminal/CommandPalette.vue')['default']
    ConnectionForm: typeof import('./src/components/connection/ConnectionForm.vue')['default']
    ContextMenu: typeof import('./src/components/common/ContextMenu.vue')['default']
    DangerBanner: typeof import('./src/components/ai/DangerBanner.vue')['default']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    ExportConnections: typeof import('./src/components/connection/ExportConnections.vue')['default']
    FileEditor: typeof import('./src/components/sftp/FileEditor.vue')['default']
    ImportSSHConfig: typeof import('./src/components/connection/ImportSSHConfig.vue')['default']
    InlineAssist: typeof import('./src/components/ai/InlineAssist.vue')['default']
    LocalFileBrowser: typeof import('./src/components/sftp/LocalFileBrowser.vue')['default']
    LockScreen: typeof import('./src/components/security/LockScreen.vue')['default']
    OnboardingWizard: typeof import('./src/components/common/OnboardingWizard.vue')['default']
    RemoteFileBrowser: typeof import('./src/components/sftp/RemoteFileBrowser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutSettings: typeof import('./src/components/settings/ShortcutSettings.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SplitContainer: typeof import('./src/components/terminal/SplitContainer.vue')['default']
    StatusBar: typeof import('./src/components/layout/StatusBar.vue')['default']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
    TerminalPane: typeof import('./src/components/terminal/TerminalPane.vue')['default']
    TransferQueue: typeof import('./src/components/sftp/TransferQueue.vue')['default']
    WelcomeView: typeof import('./src/components/layout/WelcomeView.vue')['default']
  }
}
